// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD11xYtXT3CYlpMst3hyQQwbbuU_P1Lvhw',
    appId: '1:1006486129205:web:3a71811ddb447a018b7f7c',
    messagingSenderId: '1006486129205',
    projectId: 'first-project-6c72f',
    authDomain: 'first-project-6c72f.firebaseapp.com',
    storageBucket: 'first-project-6c72f.appspot.com',
    measurementId: 'G-KT82XRWN1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx_NllcD6TsPHCxLuAIVAw2Lg0c69lgWA',
    appId: '1:1006486129205:android:95820b87c536a23d8b7f7c',
    messagingSenderId: '1006486129205',
    projectId: 'first-project-6c72f',
    storageBucket: 'first-project-6c72f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiKJ9_Vm7vjsVsQKXtYzdiREljN8Qg1dQ',
    appId: '1:1006486129205:ios:edbca7e6cc8f2a0f8b7f7c',
    messagingSenderId: '1006486129205',
    projectId: 'first-project-6c72f',
    storageBucket: 'first-project-6c72f.appspot.com',
    iosBundleId: 'com.example.promiloApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiKJ9_Vm7vjsVsQKXtYzdiREljN8Qg1dQ',
    appId: '1:1006486129205:ios:062c1174f1f7127c8b7f7c',
    messagingSenderId: '1006486129205',
    projectId: 'first-project-6c72f',
    storageBucket: 'first-project-6c72f.appspot.com',
    iosBundleId: 'com.example.promiloApp.RunnerTests',
  );
}
